Organizations:
    ###
    - &CARUNION
        Name: CARUNION # 组织的名称
        ID: CARUNIONMSP # 组织的 MSPID
        MSPDir: crypto-config/ordererOrganizations/carunion.com/msp #组织的证书相对位置（生成的crypto-config目录)
    - &ORG1
        Name: ORG1
        ID: ORG1MSP
        MSPDir: crypto-config/peerOrganizations/org1.com/msp
        AnchorPeers: # 组织锚节点的配置
            - Host: peer0.org1.com
              Port: 7051
    - &ORG2
        Name: ORG2
        ID: ORG2MSP
        MSPDir: crypto-config/peerOrganizations/org2.com/msp
        AnchorPeers: # 组织锚节点的配置
            - Host: peer0.org2.com
              Port: 7051
    
#Capabilities:
   
#    Channel: &ChannelCapabilities
        
#        V2_0: true

    
#    Orderer: &OrdererCapabilities
        
#        V2_0: true

    
#    Application: &ApplicationCapabilities
        
#        V2_5: true

Application: &ApplicationDefaults
    
    Organizations:



# 定义了排序服务的相关参数，这些参数将用于创建创世区块
Orderer: &OrdererDefaults

    
    OrdererType: solo

    
    Addresses:
        - orderer.carunion.com:7050
         #- 127.0.0.1:7050

    BatchTimeout: 2s #出块时间间隔

    BatchSize:

        MaxMessageCount: 50   #原500

        AbsoluteMaxBytes: 99 MB #原10MB
        
        PreferredMaxBytes: 5 MB

    
    MaxChannels: 0

    
    Organizations:

Profiles:

    TwoOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *CARUNION
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *ORG1
                    - *ORG2
        # 使用TwoOrgsChannel配置文件创建应用程序通道
    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *ORG1
                - *ORG2

        
           


    