version: '2.1' #docker-compose 的文件格式版本

volumes:
  orderer.carunion.com:
  peer0.org1.com:
  peer1.org1.com:
  peer0.org2.com:
  peer1.org2.com:

networks:
  fabric_network:
    name: fabric_network

services:
  # 排序服务节点
  orderer.carunion.com:
    container_name: orderer.carunion.com
    image: hyperledger/fabric-orderer:1.4.12
    environment:
      - GODEBUG=netdns=go
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      #- ORDERER_GENERAL_GENESISFILE=/root/go/src/github.com/elpsycongru/communication-system-blockchain/network/config/genesis.block # 注入创世区块
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block 
      - ORDERER_GENERAL_LOCALMSPID=CARUNIONMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp # 证书相关
    command: orderer
    ports:
      - "7050:7050"
    volumes: # 挂载由cryptogen和configtxgen生成的证书文件以及创世区块
      #- ./config/genesis.block:/root/go/src/github.com/elpsycongru/communication-system-blockchain/network/config/genesis.block
      - ./config/genesis.block:/etc/hyperledger/config/genesis.block
      - ./crypto-config/ordererOrganizations/carunion.com/orderers/orderer.carunion.com/:/etc/hyperledger/orderer
      - orderer.carunion.com:/var/hyperledger/production/orderer
    networks:
      - fabric_network

  #  MYORG 组织 peer0 节点
  peer0.org1.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org1.com
    environment:
      - CORE_PEER_ID=peer0.org1.com
      - CORE_PEER_LOCALMSPID=ORG1MSP
      - CORE_PEER_ADDRESS=peer0.org1.com:7051
    ports:
      - "7051:7051" # grpc服务端口
      - "7053:7053" # eventhub端口
    volumes:
      - ./config:/etc/hyperledger/config
      - ./crypto-config/peerOrganizations/org1.com/peers/peer0.org1.com:/etc/hyperledger/peer
      #- ./crypto-config/peerOrganizations/myorg.com/users/Admin@myorg.com:/etc/hyperledger/admin
      #- peer0.myorg.com:/var/hyperledger/production
    depends_on:
      - orderer.carunion.com
    networks:
      - fabric_network
  #  MYORG 组织 peer1 节点
  peer1.org1.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org1.com
    environment:
      - CORE_PEER_ID=peer1.org1.com
      - CORE_PEER_LOCALMSPID=ORG1MSP
      - CORE_PEER_ADDRESS=peer1.org1.com:7051
    ports:
      - "17051:7051"
      - "17053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/org1.com/peers/peer1.org1.com:/etc/hyperledger/peer
      - peer1.org1.com:/var/hyperledger/production
    depends_on:
      - orderer.carunion.com
    networks:
      - fabric_network
  #  MYORG 组织 peer2 节点
  peer0.org2.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org2.com
    environment:
      - CORE_PEER_ID=peer0.org2.com
      - CORE_PEER_LOCALMSPID=ORG2MSP
      - CORE_PEER_ADDRESS=peer0.org2.com:7051
    ports:
      - "27051:7051"
      - "27053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/org2.com/peers/peer0.org2.com:/etc/hyperledger/peer
      - peer0.org2.com:/var/hyperledger/production
    depends_on:
      - orderer.carunion.com
    networks:
      - fabric_network
  peer1.org2.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org2.com
    environment:
      - CORE_PEER_ID=peer1.org2.com
      - CORE_PEER_LOCALMSPID=ORG2MSP
      - CORE_PEER_ADDRESS=peer1.org2.com:7051
    ports:
      - "37051:7051"
      - "37053:7053"
    volumes:
      - ./crypto-config/peerOrganizations/org2.com/peers/peer1.org2.com:/etc/hyperledger/peer
      - peer1.org2.com:/var/hyperledger/production
    depends_on:
      - orderer.carunion.com
    networks:
      - fabric_network
  # 客户端节点
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.12
    tty: true
    environment:
      # go 环境设置
      - GO111MODULE=auto
      - GOPROXY=https://goproxy.cn
      - CORE_PEER_ID=cli
    command: /bin/bash
    volumes:
      #- ./config:/root/go/src/github.com/elpsycongru/communication-system-blockchain/network/config
      - ./config:/etc/hyperledger/config
      - ./crypto-config/peerOrganizations/org1.com/:/etc/hyperledger/peer/org1.com
      - ./crypto-config/peerOrganizations/org2.com/:/etc/hyperledger/peer/org2.com
      - ./../chaincode:/opt/gopath/src/chaincode # 链码路径注入
    networks:
      - fabric_network
    depends_on:
      - orderer.carunion.com
      - peer0.org1.com
      - peer1.org1.com
      - peer0.org2.com
      - peer1.org2.com
  face_recognition.app:
    build: .
    image: face_recognition:latest
    container_name: face_recognition.app
    ports:
      - "43221:43221"
    volumes:
      #- /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai
      - /Users/lichenhui/go/src/github.com/elpsycongru/communication-system-blockchain/repo/tools/facerecognition:/facerecognition

    networks:
      - fabric_network

  #fabric-realty.app:
  #  build: .
  #  image: fabric-realty/application:latest
  #  container_name: fabric-realty.app
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    #- /usr/share/zoneinfo/Asia/Shanghai:/usr/share/zoneinfo/Asia/Shanghai
  #    - ./crypto-config:/network/crypto-config
  #  networks:
  #    - fabric_network